jenkins:
  systemMessage: "Jenkins configured automatically\n\n"
  noUsageStatistics: true
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL
  slaveAgentPort: 50000
  agentProtocols:
    - "jnlp4"
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_USER}
         password: ${JENKINS_PASS}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
security:
  remotingCLI:
    enabled: false
jobs:
        - >
          pipelineJob('configuration-as-code') {
              definition {
                  cps {
                      sandbox()
                      script("""
                        stage('Checkout') {
                          git credentialsId: 'git-asos-pass', url: 'https://github.com/CollusionStudios/collusion-web-app'
                        }
                        stage('Environment') {
                          sh 'git --version'
                          echo "Branch: ${env.BRANCH_NAME}"
                          sh 'printenv'
                        }
                        stage('Build Docker test') {
                          sh 'docker build -t collusion-web-app-test -f Dockerfile.test --no-cache .'
                        }
                        stage('Run Docker test'){
                          sh 'docker run --rm collusion-web-app-test'
                        }
                        stage('Clean Docker test'){
                          sh 'docker rmi collusion-web-app-test'
                        }
                        stage('Azure Login') {
                          azureCLI commands: [[exportVariablesString: '', script: 'az group create -n MyResourceGroup --location northeurope']], principalCredentialId: 'JenkinsPrincipal'
                        }
                        stage('Deploy'){
                          sh 'docker build -t collusion-web-app -f Dockerfile.prod --no-cache .'
                          sh 'docker tag collusion-web-app localhost:5000/collusion-web-app'
                          sh 'docker push localhost:5000/collusion-web-app'
                          sh 'docker rmi -f collusion-web-app localhost:5000/collusion-web-app'
                        }
                      """.stripIndent())
                  }
              }
          }

# TODO: include this once supported
# unclassified:
#   simple-theme-plugin:
#     cssUrl: "https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-blue-grey.css"
#     faviconUrl: "https://collusion.com/favicon.ico"
