jenkins:
  systemMessage: "Jenkins configured automatically\n\n"
  noUsageStatistics: true
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL
  slaveAgentPort: 50000
  agentProtocols:
    - "jnlp4"
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_USER}
         password: ${JENKINS_PASS}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope:    SYSTEM
              id:       github_collusion
              description: github_collusion
              username: ${GITHUB_USER}
              password: ${GITHUB_PASS}
security:
  remotingCLI:
    enabled: false
jobs:
        - >
          pipelineJob('configuration-as-code') {
              definition {
                  cps {
                      sandbox()
                      script("""
                        node {
                          stage('Checkout') {
                            git branch: 'acceptance-tests', credentialsId: 'github_collusion', url: 'https://github.com/CollusionStudios/collusion-web-app'
                          }
                          stage('Environment') {
                            sh 'git --version' 
                            sh 'printenv'
                          }
                          stage('Unit tests') {
                            sh 'docker build -t collusion-web-app-test -f Dockerfile.test --no-cache .' 
                            sh 'docker run --rm collusion-web-app-test' 
                            sh 'docker rmi collusion-web-app-test'
                          }
                          stage('E2E tests') {
                            sh 'docker build -t collusion-web-app-ui-tests -f Dockerfile.uitest --no-cache .' 
                            sh 'docker run -e SAUCE_USERNAME=\${SAUCE_USERNAME} -e SAUCE_ACCESS_KEY=\${SAUCE_ACCESS_KEY} --rm collusion-web-app-ui-tests' 
                            sh 'docker rmi collusion-web-app-ui-tests' 
                          }
                          stage('Build') {
                            sh 'docker login \${COLLUSION_REGISTRY_URL} -u \${COLLUSION_REGISTRY_USERNAME} -p \${COLLUSION_REGISTRY_PASS}' 
                            sh 'docker build -t collusion-web-app -f Dockerfile.prod --no-cache .' 
                            sh 'docker tag collusion-web-app \${COLLUSION_REGISTRY_URL}/collusion-web-app:dev' 
                            sh 'docker push \${COLLUSION_REGISTRY_URL}/collusion-web-app' 
                            sh 'docker rmi -f \${COLLUSION_REGISTRY_URL}/collusion-web-app:dev' 
                          }
                        }
                      """.stripIndent())
                  }
              }
          }

# TODO: include this once supported
# unclassified:
#   simple-theme-plugin:
#     cssUrl: "https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-blue-grey.css"
#     faviconUrl: "https://collusion.com/favicon.ico"
